### ISSUE TITLE
Update walksheds when school is moved

### ISSUE THREAD

**Issue by TimReardon** [MAPC/myschoolcommute#38]
The script to regenerate walksheds should be automatically run when a user hits "save" on the schools admin page (e.g., http://masaferoutessurvey.com/en/admin/survey/school/16/).  This does not need to be available on the user-facing schools page since district officials do not have, and do not need to have, the ability to edit the location of their school.

**Comment by demiurg** [comment]
I tested this in production, sheds are regenerating when school is moved through the admin interface. This required upgrading to pgrouting 2.0 and updating queries, because for some reason pgrouting 1 functions were not longer working.
