### ISSUE TITLE
Adding news schools or updating school geometries throws 500 server error (partially fixed)

### ISSUE THREAD

**Issue by allthesignals** [MAPC/myschoolcommute#77]
Site should continue to function when school records are inserted or geometries updated through the Django admin interface. 

Tasks:
- [x] Updating school geometries
- [x] Adding new schools

**Comment by allthesignals** [comment]
https://github.com/MAPC/myschoolcommute/blob/master/survey/models.py#L71 Adding `default=False` here seems to resolve this problem.

**Comment by allthesignals** [comment]
@demiurg Hi Pavel - after pulling in code changes and setting a default value, I'm now seeing:
```
TypeError at /en/admin/survey/school/add/
int() argument must be a string or a number, not 'NoneType'
```
When adding new schools locally. In production, adding schools still throws a server error (500). Any updates for this issue on your front?

Thanks!

**Comment by allthesignals** [comment]
Hi @demiurg, 
Any updates on this issue? Thanks!

**Comment by demiurg** [comment]
Not yet, I will look at it today.

**Comment by demiurg** [comment]
Well, it looked like default wasn't added, maybe it got lost in merge. Can you try testing and pushing, to see if there is still any error?

**Comment by allthesignals** [comment]
That's right - the default wasn't added. I tested it and it still produces
an error.

On Wed, Mar 18, 2015 at 1:10 PM, Pavel <notifications@github.com> wrote:

> Well, it looked like default wasn't added, maybe it got lost in merge. Can
> you try testing and pushing, to see if there is still any error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MAPC/myschoolcommute/issues/77#issuecomment-83061210>.
>



-- 
Matt Gardner
M.S. Urban and Regional Policy Candidate
School of Public Policy and Urban Affairs
Northeastern University

**Comment by allthesignals** [comment]
@demiurg I went ahead and pushed the code that includes `default=False` on the School model, which, like I said, still produces the TypeError. Let me know how I can help.

Thank you!

**Comment by demiurg** [comment]
Ok, I actually added default to wrong field, fixed now, and sheds were not generating, which they do now.  Just tested and works, can you try again?

**Comment by allthesignals** [comment]
@demiurg Great - thanks, Pavel. I pulled and tested, and I'm seeing an SRID error, which is related to my local database. I know I was struggling with this problem earlier, so I think it's unrelated because it's trying the shed generation. 

`GetProj4StringSPI: Cannot find SRID (900914) in spatial_ref_sys`

I would say it's probably safe to pull into production if it works for you (my local copy of the database needs some work - the restoration was not perfect anyway).

**Comment by demiurg** [comment]
Have you tried the insert query from another issue?

**Comment by allthesignals** [comment]
I did. But I'll double check in the morning. Thanks!

On Wednesday, March 18, 2015, Pavel <notifications@github.com> wrote:

> Have you tried the insert query from another issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MAPC/myschoolcommute/issues/77#issuecomment-83160189>.
>


-- 
Matt Gardner
M.S. Urban and Regional Policy Candidate
School of Public Policy and Urban Affairs
Northeastern University

**Comment by demiurg** [comment]
Well, the error basically says the row with that srid is not in that table. Perhaps there was an error inserting because of permissions.

**Comment by allthesignals** [comment]
@demiurg Hi Pavel - are you able to add schools locally without error? Thanks!

**Comment by demiurg** [comment]
I was, added without error for me. This is pulled to production now. If a school with real data gets added, and surveys and report work, then it can be considered working.

**Comment by allthesignals** [comment]
Excellent. I can successfully add schools. Thanks!

On Mon, Mar 23, 2015 at 10:51 AM, Pavel <notifications@github.com> wrote:

> I was, added without error for me. This is pulled to production now. If a
> school with real data gets added, and surveys and report work, then it can
> be considered working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MAPC/myschoolcommute/issues/77#issuecomment-85033862>.
>



-- 
Matt Gardner
M.S. Urban and Regional Policy Candidate
School of Public Policy and Urban Affairs
Northeastern University

**Comment by allthesignals** [comment]
@demiurg Hi Pavel - not sure where this fits, but it looks like there's a static join table called school_muni that crosswalks schid with muni_id. When new schools are added, their schids aren't inserted into the join table, so batch entry can't call `get_intersections` on the School model. Anyway, I'm not sure if you're aware of this, but it does affect how usable the site is after adding schools.

**Comment by demiurg** [comment]
I did not go through the uses of school, but that sounds like a good example problem. I think the spatial data would be necessary to make the spatial search work this automatically. It would be easier to make SchoolTown model be a required relationship in the admin interface, and it would require knowing this information.
