### ISSUE TITLE
Attempt to edit user through admin console throws bad gateway error. 

### ISSUE THREAD

**Issue by TimReardon** [MAPC/myschoolcommute#84]
Admin console is throwing a 502 Bad Gateway error when I attempt to edit the record for an individual user.  Noticed it when trying to edit a new user (http://masaferoutessurvey.org/en/admin/auth/user/101/) but same error occurs no matter which user I am trying to edit. Can view and edit survey records OK.  
@allthesignals can you help diagnose?

**Comment by allthesignals** [comment]
Hi @demiurge, 

I looked at the error logs for this. Every time we look to edit a user, `saferoutes-gunicorn.log` shows this:
```
[myschoolcommute] $ Error opening file for reading: Permission denied
2015-08-21 16:36:55 [18007] [CRITICAL] WORKER TIMEOUT (pid:27484)
2015-08-21 16:36:55 [18007] [CRITICAL] WORKER TIMEOUT (pid:27484)
2015-08-21 16:36:55 [27521] [INFO] Booting worker with pid: 27521
Error opening file for reading: Permission denied
```
Any thoughts on how we might troubleshoot this? Perhaps the file permission is related to error logging and not this specific issue. Additionally, I'm guess it could be a timeout limit set somewhere in the settings. I remember this being functional before the last major push, but I don't think those changes affected users or administration.

Thank you!

Best,
Matt

**Comment by demiurg** [comment]
I would try modifying the user model from console and seeing what happens there. I do remember some special trigger logic on some model save events.

**Comment by allthesignals** [comment]
Thanks, @demiurg. I went ahead and made the change I needed through the ORM. Thankfully, the model seems to be in working order. The issue must be with the edit view. I could try running a few of the view methods to see if I can reproduce the issue.

**Comment by arouault** [comment]
Interface has been retired.
